### ISSUE TITLE
qiskit.providers.ibmq.exceptions.IBMQAccountCredentialsNotFound: 'No IBM Quantum Experience credentials found.'

### ISSUE THREAD

**Issue by Turningl** [mit-han-lab/torchquantum#199]
when  I run mnist.py, some bugs as follow:
```
Epoch 1:
0.005
valid set accuracy: 0.816597510373444
valid set loss: 0.5205235481262207
Epoch 2:
0.0025
valid set accuracy: 0.8365145228215768
valid set loss: 0.49810928106307983
test set accuracy: 0.8266666666666667
test set loss: 0.5145555138587952

Test with Qiskit Simulator
Traceback (most recent call last):
  File "/home/zl/torchquantum-main/examples/mnist/mnist.py", line 281, in <module>
    main()
  File "/home/zl/torchquantum-main/examples/mnist/mnist.py", line 253, in main
    processor_simulation = QiskitProcessor(use_real_qc=False)
  File "/home/zl/.conda/envs/quantum/lib/python3.8/site-packages/torchquantum-0.1.7-py3.8.egg/torchquantum/plugin/qiskit/qiskit_processor.py", line 142, in __init__
    self.qiskit_init()
  File "/home/zl/.conda/envs/quantum/lib/python3.8/site-packages/torchquantum-0.1.7-py3.8.egg/torchquantum/plugin/qiskit/qiskit_processor.py", line 194, in qiskit_init
    IBMQ.load_account()
  File "/home/zl/.conda/envs/quantum/lib/python3.8/site-packages/qiskit/providers/ibmq/ibmqfactory.py", line 167, in load_account
    raise IBMQAccountCredentialsNotFound(
qiskit.providers.ibmq.exceptions.IBMQAccountCredentialsNotFound: 'No IBM Quantum Experience credentials found.'
```
how can I solve it?

**Comment by GenericP3rson** [comment]
Hey! To test with qiskit simulator and the real quantum computer, you'll need an IBMQ account. You can find some details on how to get and save credentials [here](https://qiskit.org/ecosystem/ibm-runtime/how_to/account-management.html). If you have any further questions, feel free to reach out!

**Comment by GenericP3rson** [comment]
Hi! I’m going to close this issue for now, but if you have any further questions or difficulties, please don’t hesitate to reach out and/or follow-up!

**Comment by Hanrui-Wang** [comment]
Thanks a lot [GenericP3rson](https://github.com/GenericP3rson) for helping answer!
