### ISSUE TITLE
RuntimeError: Trying to create tensor with negative dimension -6880: [10, -6880]

### ISSUE THREAD

**Issue by easonoob** [mit-han-lab/torchquantum#214]
I was trying this library (great works btw!) when I got the following error:
```
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    predictions = model(input_embeddings)
  File "/home/eason/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eason/Documents/AI/ESNN/v-2-0/prototype.py", line 146, in forward
    segment_output.append(cluster(q_device, segment_embeddings))
  File "/home/eason/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eason/Documents/AI/ESNN/v-2-0/prototype.py", line 74, in forward
    self.encoder(q_device, reshaped_input_states)
  File "/home/eason/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eason/anaconda3/envs/ldm/lib/python3.8/site-packages/torchquantum/encoding.py", line 164, in forward
    torch.zeros(
RuntimeError: Trying to create tensor with negative dimension -6880: [10, -6880]
```
The shape of reshape_input_states is `torch.Size([10, 6912])`. Any helps will be welcomed!

**Comment by GenericP3rson** [comment]
Hey! Could you send some code to replicate the error? If so, I can what I can do!

**Comment by easonoob** [comment]
I think I figured it out, 2^n_wires needs to be larger than the feature size of x in the forward function of StateEncoder.
