### ISSUE TITLE
Unable to install requirements 

### ISSUE THREAD

**Issue by aviralsangal8** [mit-han-lab/torchquantum#225]
Got the following error:

 Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Aviral\.conda\envs\quantum5g\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Aviral\.conda\envs\quantum5g\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Aviral\.conda\envs\quantum5g\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Aviral\AppData\Local\Temp\pip-build-env-8pmowbp7\overlay\Lib\site-packages\sphinx_theme_builder\__init__.py", line 80, in prepare_metadata_for_build_wheel
          return _generate_metadata(project, destination=Path(metadata_directory))
        File "C:\Users\Aviral\AppData\Local\Temp\pip-build-env-8pmowbp7\overlay\Lib\site-packages\sphinx_theme_builder\_internal\distributions.py", line 132, in generate_metadata
          (dist_info / "METADATA").write_text(project.get_metadata_file_contents())
        File "C:\Users\Aviral\.conda\envs\quantum5g\lib\pathlib.py", line 1155, in write_text
          return f.write(data)
        File "C:\Users\Aviral\.conda\envs\quantum5g\lib\encodings\cp1252.py", line 19, in encode
          return codecs.charmap_encode(input,self.errors,encoding_table)[0]
      UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f389' in position 3864: character maps to <undefined>

**Comment by GenericP3rson** [comment]
Interesting, I haven’t seen this before. What environment are you using?
