### ISSUE TITLE
NameError: name 'mat_dict' is not defined

### ISSUE THREAD

**Issue by yezhuoyang** [mit-han-lab/torchquantum#226]
In the develop branch, I try to run the mnist example in the file examples/mnist/minst.py

Here is the bug of running the code:

```console
Traceback (most recent call last):
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\examples\mnist\mnist.py", line 281, in <module>
    main()
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\examples\mnist\mnist.py", line 236, in main
    train(dataflow, model, device, optimizer)
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\examples\mnist\mnist.py", line 142, in train
    outputs = model(inputs)
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\examples\mnist\mnist.py", line 128, in forward
    self.q_layer(qdev)
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\examples\mnist\mnist.py", line 70, in forward
    qdev.sx(wires=2)  # type: ignore
  File "C:\Users\yezhu\OneDrive\Desktop\torchquantum\torchquantum\functional\sx.py", line 85, in sx
    mat = mat_dict[name]
NameError: name 'mat_dict' is not defined
```

There is an unresolved reference of 'mat_dict' in the file "\torchquantum\functional\sx.py".

**Comment by GenericP3rson** [comment]
Thanks for catching this issue! This is actually resolved in https://github.com/mit-han-lab/torchquantum/pull/206 (specifically https://github.com/mit-han-lab/torchquantum/pull/206/commits/ffaaefa6bfcfccd9dbd6e991acf3fc196f00a852), so it shouldn’t be a problem once the PR is merged in!

**Comment by GenericP3rson** [comment]
Marking as closed, resolved in the most recent release!
