### ISSUE TITLE
Fail to install pyscf on Windows11

### ISSUE THREAD

**Issue by MinqiShao** [mit-han-lab/torchquantum#277]
When I tried to install torchquantum on windows11 and run requirements, I got errors as follows:
Building wheels for collected packages: pyscf
  Building wheel for pyscf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyscf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      running bdist_wheel
      running build
      running build_py
      cmake -SC:\Users\minqi\AppData\Local\Temp\pip-req-build-374epm_b\pyscf\lib -Bbuild\temp.win-amd64
      -- Building for: Visual Studio 17 2022
      -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
      -- The C compiler identification is MSVC 19.39.33523.0
      -- The CXX compiler identification is MSVC 19.39.33523.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Looking for sgemm_
      -- Looking for sgemm_ - not found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - not found
      -- Found Threads: TRUE
      -- Could NOT find BLAS (missing: BLAS_LIBRARIES)
      -- Looking for ffsll
      -- Looking for ffsll - not found
      CMake Error at CMakeLists.txt:76 (message):
        A required library with BLAS API not found.

      -- Configuring incomplete, errors occurred!
      error: command 'C:\\Users\\minqi\\AppData\\Local\\Temp\\pip-build-env-8wpn9jvl\\overlay\\Scripts\\cmake.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyscf
Failed to build pyscf
ERROR: Could not build wheels for pyscf, which is required to install pyproject.toml-based projects

Besides, I tried to run Basic usage after installing other all requirements, and I got errors as follows:
Traceback (most recent call last):
  File "C:\Users\minqi\OneDrive\デスクトップ\reps\torchquantum\BasicUsage.py", line 1, in <module>
    import torchquantum as tq
  File "C:\Users\minqi\OneDrive\デスクトップ\reps\torchquantum\torchquantum\__init__.py", line 29, in <module>
    from .device import *
  File "C:\Users\minqi\OneDrive\デスクトップ\reps\torchquantum\torchquantum\device\__init__.py", line 25, in <module>
    from .devices import *
  File "C:\Users\minqi\OneDrive\デスクトップ\reps\torchquantum\torchquantum\device\devices.py", line 30, in <module>
    from torchquantum.functional import func_name_dict, func_name_dict_collect
  File "C:\Users\minqi\OneDrive\デスクトップ\reps\torchquantum\torchquantum\functional\__init__.py", line 25, in <module>
    from .gate_wrapper import gate_wrapper, apply_unitary_einsum, apply_unitary_bmm
  File "C:\Users\minqi\OneDrive\デスクトップ\reps\torchquantum\torchquantum\functional\gate_wrapper.py", line 7, in <module>
    from ..util.utils import pauli_eigs, diag
  File "C:\Users\minqi\OneDrive\デスクトップ\reps\torchquantum\torchquantum\util\__init__.py", line 25, in <module>
    from .utils import *
  File "C:\Users\minqi\OneDrive\デスクトップ\reps\torchquantum\torchquantum\util\utils.py", line 33, in <module>
    from qiskit_ibm_runtime import QiskitRuntimeService
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\qiskit_ibm_runtime\__init__.py", line 179, in <module>
    from .qiskit_runtime_service import QiskitRuntimeService
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\qiskit_ibm_runtime\qiskit_runtime_service.py", line 32, in <module>
    from qiskit_ibm_runtime import ibm_backend
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\qiskit_ibm_runtime\ibm_backend.py", line 44, in <module>
    from .provider_session import (
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\qiskit_ibm_runtime\provider_session.py", line 19, in <module>
    from .utils.converters import hms_to_seconds
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\qiskit_ibm_runtime\utils\__init__.py", line 45, in <module>
    from .utils import to_python_identifier, is_crn, get_runtime_api_base_url, resolve_crn
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\qiskit_ibm_runtime\utils\utils.py", line 26, in <module>
    import requests
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\requests\__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\requests\api.py", line 11, in <module>
    from . import sessions
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\requests\sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\requests\adapters.py", line 76, in <module>
    _preloaded_ssl_context = create_urllib3_context()
  File "C:\Users\minqi\anaconda3\envs\torchquantum\lib\site-packages\urllib3\util\ssl_.py", line 252, in create_urllib3_context
    raise TypeError("Can't create an SSLContext object without an ssl module")
TypeError: Can't create an SSLContext object without an ssl module

Can you help me? Thank you very much!

**Comment by ElinRanjan** [comment]
Did you find a solution?
