### ISSUE TITLE
Testing of mnist_example_no_binding.py file produces error

### ISSUE THREAD

**Issue by manu123416** [mit-han-lab/torchquantum#38]
Hi,
I tried testing the mnist_example_no_binding.py file. I keep getting the below error:
```
  File "C:\Users\manuc\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py", line 126, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\manuc\AppData\Local\Programs\Python\Python39\
lib\site-packages\torch\lib\cusparse64_11.dll" or one of its dependencies.
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>

```
Please suggest me a way to resolve this. Because of this error, my testing is not yet complete.

**Comment by Hanrui-Wang** [comment]
Hi manu123416,

Thank you for your feedback! Could you provide more information about the execution environment you are using?

**Comment by manu123416** [comment]
Hi Hanrui-Wang,
I was trying to test it on pycharm environment.

**Comment by Hanrui-Wang** [comment]
Is that on a Windows machine?

**Comment by manu123416** [comment]
Yes, I am using windows machine. I somehow made things working at Jupyter notebook now. I think, now I can close the issue.
